## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Discription
0,0,Ushuaia,AR,2022-05-06 22:08:23,-54.8000,-68.3000,42.46,65,40,20.71,scattered clouds
1,1,Punta Arenas,CL,2022-05-06 22:09:38,-53.1500,-70.9167,44.71,81,100,9.22,light rain
2,2,New Norfolk,AU,2022-05-06 22:12:05,-42.7826,147.0587,49.66,77,100,1.99,light rain
3,3,Longyearbyen,SJ,2022-05-06 22:12:06,78.2186,15.6401,26.44,68,75,5.75,broken clouds
4,4,Houma,US,2022-05-06 22:09:04,29.5958,-90.7195,89.01,71,1,12.35,clear sky

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 80

In [5]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Discription
5,5,Arraial Do Cabo,BR,2022-05-06 22:12:07,-22.9661,-42.0278,73.26,73,0,16.11,clear sky
7,7,Bengkulu,ID,2022-05-06 22:09:40,-3.8004,102.2655,76.03,89,100,6.22,overcast clouds
13,13,Rikitea,PF,2022-05-06 22:09:39,-23.1203,-134.9692,77.59,84,84,16.17,moderate rain
15,15,Sao Joao Da Barra,BR,2022-05-06 22:09:33,-21.6403,-41.0511,73.38,71,29,15.70,scattered clouds
19,19,Matara,LK,2022-05-06 22:12:13,5.9485,80.5353,79.54,90,100,8.46,overcast clouds
23,23,Mackay,AU,2022-05-06 22:12:15,-21.1500,149.2000,74.68,84,100,8.16,overcast clouds
25,25,Karratha,AU,2022-05-06 22:12:16,-20.7377,116.8463,74.70,46,4,18.81,clear sky
26,26,Lompoc,US,2022-05-06 22:12:17,34.6391,-120.4579,78.69,66,0,32.01,clear sky
33,33,Puerto Ayora,EC,2022-05-06 22:08:09,-0.7393,-90.3518,76.96,82,88,8.57,overcast clouds
37,37,Suleja,NG,2022-05-06 22:12:25,9.1758,7.1808,74.82,77,100,2.51,overcast clouds

In [6]:
preferred_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 5 to 656
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              158 non-null    int64
 1   City                 158 non-null    object
 2   Country              158 non-null    object
 3   Date                 158 non-null    object
 4   Lat                  158 non-null    float64
 5   Lng                  158 non-null    float64
 6   Max Temp             158 non-null    float64
 7   Humidity             158 non-null    int64
 8   Cloudiness           158 non-null    int64
 9   Wind Speed           158 non-null    float64
 10  Weather Discription  158 non-null    object
dtypes: float64(4), int64(3), object(4)
memory usage: 14.8+ KB

In [7]:
preferred_cities_df.dropna(how="any")

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Discription
5,5,Arraial Do Cabo,BR,2022-05-06 22:12:07,-22.9661,-42.0278,73.26,73,0,16.11,clear sky
7,7,Bengkulu,ID,2022-05-06 22:09:40,-3.8004,102.2655,76.03,89,100,6.22,overcast clouds
13,13,Rikitea,PF,2022-05-06 22:09:39,-23.1203,-134.9692,77.59,84,84,16.17,moderate rain
15,15,Sao Joao Da Barra,BR,2022-05-06 22:09:33,-21.6403,-41.0511,73.38,71,29,15.70,scattered clouds
19,19,Matara,LK,2022-05-06 22:12:13,5.9485,80.5353,79.54,90,100,8.46,overcast clouds
...,...,...,...,...,...,...,...,...,...,...,...
640,640,Ajuterique,HN,2022-05-06 22:35:54,14.3833,-87.7000,77.16,82,77,3.94,broken clouds
643,643,Sao Felix Do Xingu,BR,2022-05-06 22:35:55,-6.6447,-51.9950,75.20,90,59,3.02,broken clouds
646,646,Ampanihy,MG,2022-05-06 22:35:57,-24.7000,44.7500,71.53,74,20,5.41,few clouds
653,653,Palasa,IN,2022-05-06 22:35:59,18.7667,84.4167,79.74,86,34,4.05,scattered clouds
656,656,Teacapan,MX,2022-05-06 22:37:01,22.5500,-105.7500,79.86,57,2,8.97,clear sky

In [8]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather Discription" , "Lat", "Lng"]].copy()
#Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Discription,Lat,Lng,Hotel Name
5,Arraial Do Cabo,BR,73.26,clear sky,-22.9661,-42.0278,
7,Bengkulu,ID,76.03,overcast clouds,-3.8004,102.2655,
13,Rikitea,PF,77.59,moderate rain,-23.1203,-134.9692,
15,Sao Joao Da Barra,BR,73.38,scattered clouds,-21.6403,-41.0511,
19,Matara,LK,79.54,overcast clouds,5.9485,80.5353,
23,Mackay,AU,74.68,overcast clouds,-21.1500,149.2000,
25,Karratha,AU,74.70,clear sky,-20.7377,116.8463,
26,Lompoc,US,78.69,clear sky,34.6391,-120.4579,
33,Puerto Ayora,EC,76.96,overcast clouds,-0.7393,-90.3518,
37,Suleja,NG,74.82,overcast clouds,9.1758,7.1808,

In [9]:
#Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params)
print(hotels.status_code)
place_data=hotels.json()
print(place_data["results"][0]["name"])

200
Hôtel Duo

In [14]:
#Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key}

hotel_names=[]
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
# Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
 
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params)
    #Error handling
    if (hotels.status_code==200):
        place_data=hotels.json()
     
        if (len(place_data["results"]) > 0):
            hotel_names.append(place_data["results"][0]["name"])
        
        else:
            hotel_names.append("")
    else:
            hotel_names.append("")
        
hotel_df["Hotel Name"]=hotel_names
hotel_df.head(10)

,City,Country,Max Temp,Weather Discription,Lat,Lng,Hotel Name
5,Arraial Do Cabo,BR,73.26,clear sky,-22.9661,-42.0278,Pousada Porto Praia
7,Bengkulu,ID,76.03,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
13,Rikitea,PF,77.59,moderate rain,-23.1203,-134.9692,People ThankYou
15,Sao Joao Da Barra,BR,73.38,scattered clouds,-21.6403,-41.0511,Pousada Porto De Canoas
19,Matara,LK,79.54,overcast clouds,5.9485,80.5353,Amaloh Boutique Resort
23,Mackay,AU,74.68,overcast clouds,-21.1500,149.2000,International Lodge Motel
25,Karratha,AU,74.70,clear sky,-20.7377,116.8463,ibis Styles Karratha
26,Lompoc,US,78.69,clear sky,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
33,Puerto Ayora,EC,76.96,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
37,Suleja,NG,74.82,overcast clouds,9.1758,7.1808,Capy Motel

In [15]:
# Drop the rows where there is no Hotel Name
hotel_df.loc[hotel_df["Hotel Name"] !=""]

,City,Country,Max Temp,Weather Discription,Lat,Lng,Hotel Name
5,Arraial Do Cabo,BR,73.26,clear sky,-22.9661,-42.0278,Pousada Porto Praia
7,Bengkulu,ID,76.03,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
13,Rikitea,PF,77.59,moderate rain,-23.1203,-134.9692,People ThankYou
15,Sao Joao Da Barra,BR,73.38,scattered clouds,-21.6403,-41.0511,Pousada Porto De Canoas
19,Matara,LK,79.54,overcast clouds,5.9485,80.5353,Amaloh Boutique Resort
...,...,...,...,...,...,...,...
640,Ajuterique,HN,77.16,broken clouds,14.3833,-87.7000,M&M Zavala Hotel and B&B
643,Sao Felix Do Xingu,BR,75.20,broken clouds,-6.6447,-51.9950,Rio Xingu Camping
646,Ampanihy,MG,71.53,few clouds,-24.7000,44.7500,Angora Hotel
653,Palasa,IN,79.74,scattered clouds,18.7667,84.4167,Balaji tifen & meals veg & non veg hotel
656,Teacapan,MX,79.86,clear sky,22.5500,-105.7500,Hotel los Mangos

In [17]:
#  Export the City_Data into a csv
# Create the output file (CSV).
output_data_file = "Weather_Database/.csv"
# Export the City_Data into a CSV.

hotel_df.to_csv(output_data_file, index_label="City_ID")

In [18]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [20]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))